### ISSUE TITLE
it is not working 

### ISSUE THREAD

**Issue by RAZAA12** [mgoricki/apex-plugin-master-detail-item#1]
i'm exactly doing the same way as you suggested but not working , what could be the problem???

**Comment by mgoricki** [comment]
How could I help you with information that you provided me. 
Can you make example on apex.oracle.com? What APEX version are you using?

**Comment by orabin** [comment]
Can I attach a screenshot of the plugin insert in the test application?

**Comment by RAZAA12** [comment]
no thanks i have done it

**Comment by orabin** [comment]
@RAZAA12 It is possible to paint a little more subgenre this phrase  "Create Master-Detail Plugin Item and set Master and Detail Report ID's to ones defined in master and detail report regions."

**Comment by mgoricki** [comment]
Closing the issue because problem is unknown.
