### ISSUE TITLE
Detailed report remains empty

### ISSUE THREAD

**Issue by orabin** [mgoricki/apex-plugin-master-detail-item#2]
Apex 5.1.3. I did everything according to your instructions.
Master - IR (based on view)
Detail - IG

"IMPORTANT: for Interactive Report regions you have to set column property Static ID to MASTER_ID"
When I fill this field in the IR, the field disappears from the report wizard. When moving through the main report, the detailed report remains empty.

**Comment by orabin** [comment]
I created a test application. Three regions (for variables, master - IR, detail - CR).
A detailed classic report does not display anything.

What am I doing wrong?

**Comment by mgoricki** [comment]
You have to use Master-detail Item in where condition of detail region.

**Comment by orabin** [comment]
Thank. I wish you new wonderful plugins!
