### ISSUE TITLE
I have try this plug in in Oracle APEX 5.1.4 but its not working as you mention in Demo

### ISSUE THREAD

**Issue by ymusani** [mgoricki/apex-plugin-master-detail-item#3]

**Comment by mgoricki** [comment]
I can't help you with the information that you provided. There's demo on apex.oracle.com (on 5.1.4) that works fine: https://apex.oracle.com/pls/apex/f?p=masterdetailitem

**Comment by mgoricki** [comment]
Closed, because there's no response from ymusani.
